# Generated by Django 4.2.1 on 2023-05-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='gender',
            new_name='status',
        ),
    ]
