version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accuknox-rishabh-jain
    image: rishabh-jain:social-media-app
    ports:
      - 8000:8000
    volumes:
      - .:/app
  